codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

flags:
  unittests:
    paths:
      - src/vnstock_mcp/
    carryforward: true

ignore:
  - "test/"
  - "tests/"
  - "htmlcov/"
  - "*.pyc"
  - "__pycache__/"
